import * as React from 'react';
import { DefaultButton } from '@fluentui/react';
import { HistorialPanel, IHistorialItem } from './components/HistorialPanel';
import { initializeIcons } from '@fluentui/react/lib/Icons';
import Historial from './components/Historial/Historial'

initializeIcons();


const App: React.FC = () => {
  const [isPanelOpen, setIsPanelOpen] = React.useState(false);

  const items: IHistorialItem[] = [
    {
      estadoUnico: 'Estado único de prueba',
      // estadoAnterior: 'Borrador',
      // estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.comMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER AGREGO PARA ROMPER ',
    },
    {
      estadoAnterior: '',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: null,
      estadoPosterior: null,
      usuario: null,
      fecha: null,
      hora: null,
      observacion: null,
    },
    {
      usuario: 'CASO SIN ESTADO',
      fecha: null,
      hora: null,
      observacion: null,
    },
    {
      estadoUnico: '1',
      estadoAnterior: '2',
      estadoPosterior: '3',
      usuario: 'CASO con 3 ESTADOS',
      fecha: null,
      hora: null,
      observacion: null,
    },
    ,
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: '',
      usuario: 'ab',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: '',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: null,
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPAFin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: 'Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA',
    },
    {
      estadoAnterior: 'Borrador',
      estadoPosterior: 'Publicado',
      usuario: 'agustin.brocani@outlook.com',
      fecha: '29-05-2025',
      hora: '14:30',
      observacion: 'Se aprobó el cambio',
    },
    {
      estadoAnterior: 'Publicado',
      estadoPosterior: 'Archivado',
      usuario: 'admin.system',
      fecha: '30-05-2025',
      hora: '14:30',
      observacion: '[U]Fin del ciclo de vida AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA AGREGO ESTE CODIGO PARA QUE SEA LARGO Y SI TIENE QUE ROMPER, SE ROMPA ',
    },
  ];

  return (
    <div style={{ padding: 20 }}>
      {/* <DefaultButton text="Ver Historial" onClick={() => isPanelOpen ? setIsPanelOpen(false) : setIsPanelOpen(true)} />
      <HistorialPanel
        isOpen={isPanelOpen}
        onDismiss={() => isPanelOpen ? setIsPanelOpen(false) : setIsPanelOpen(true)}
        items={items}
      /> */}

      <Historial
        items={items}
        colorGeneral='#0078d4'
        colorAvatar='#c4314b'
        textoEncabezadoHistorial={'Historial de cambios'}
        // leyendaToolTip='Historial'
        // estilosBoton={{
        //   root: {
        //     color: '#0078d4',
        //     width: 30,
        //     height: 30,
        //     border: '1px solid #0078d4',
        //     borderRadius: 6,
        //   }
        // }}
        onClose={() => console.log('Cerré la ventana lateral.')}
      />

    </div>
  );
};

export default App;
